Fixed a bug where ``mne.io.read_raw_gdf`` failed with NumPy â‰¥1.24 due to the removal of ``np.fromstring`` binary mode. Replaced with ``np.frombuffer`` for compatibility. (:newcontrib:`devparikh0506`)